[target.x86_64-unknown-linux-gnu]
image = "ubuntu:24.04"
pre-build = [
    "export DEBIAN_FRONTEND=noninteractive",
    "export TZ=Etc/UTC",
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update -q && apt-get install --assume-yes --no-install-recommends build-essential",
]

# TODO: Make sure this works on macOS
[target.aarch64-unknown-linux-gnu]
pre-build = [
    "export DEBIAN_FRONTEND=noninteractive",
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update -q && apt-get install --assume-yes --no-install-recommends pkg-config",
]