[package]
name = "zksync_error"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["std", "use_anyhow", "use_serde"]
std = [ "serde/std", "lazy_static/spin_no_std", "anyhow?/std", "strum/std"]
use_anyhow = ["dep:anyhow"]
use_serde = ["dep:serde"]
runtime_documentation = ["dep:serde", "dep:serde_json"]
serialized_errors = ["dep:serde", "dep:serde_json"]
packed_errors = ["use_serde"]


[dependencies]
anyhow = { workspace = true, optional = true }
lazy_static = { version = "1.5.0", default-features = false, optional = true }
serde = { version = "1.0.210", features = [ "derive", "alloc" ], default-features = false, optional = true }
serde_json = { version = "1.0.128", optional = true }
strum = { version = "0.26.3", default-features = false, features = ["derive"] }
strum_macros = { version = "0.26.4", default-features = false }

zksync_basic_types.workspace = true
zksync-error-description.workspace = true

[build-dependencies]
zksync-error-codegen = { workspace = true, features = ["reqwest-rustls-tls"] }
