name: cargo-deny check
on: pull_request
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@8d73959fce1cdc8989f23fdf03bec6ae6a6576ef # v2.0.7
      with:
        manifest-path: "./Cargo.toml"
        command: check
        command-arguments: "--hide-inclusion-graph"
