name: checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # ensures proper formatting and clippy lint
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Run Linters
        run: |
          cargo fmt --all -- --check &&
          cargo clippy -Zunstable-options -- -D warnings --allow clippy::unwrap_used

  # ensures build is successful
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Build Code
        run: make all