name: Testing era_test_node using e2e
on:
  workflow_call:

permissions:
  statuses: write
  checks: write
  actions: write

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: e2e
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: era_test_node-ubuntu-latest.tar.gz
      
      - name: Start the era_test_node
        id: start_node
        run: |
          echo "Extracting era_test_node binary"
          tar -xzf era_test_node-ubuntu-latest.tar.gz
          chmod +x era_test_node
          echo "Starting node in background"
          ./era_test_node run 2>&1 | tee era_test_node_ouput.log &
          echo "PID=$!" >> $GITHUB_ENV

      - name: Launch tests
        id: launch
        run: |
          echo "Run tests"
          make test-e2e

      - name: Stop the era_test_node and print output logs
        id: stop_node
        if: always()
        run: |
          cat era_test_node_ouput.log
          kill $PID

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          path: ./e2e-tests/test-results.json
          name: E2E Test Results
          reporter: 'mocha-json'
