name: run
on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: e2e
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Era Test Node
        uses: dutterbutter/era-test-node-action@latest

      - name: Launch tests
        id: launch
        run: |
          echo "Run tests"
          make test-e2e

      - name: Print output logs
        if: always()
        run: |
          cat era_test_node_ouput.log
