name: run

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: unit-tests
    runs-on: ubuntu-latest

    steps:

      - name: Slack notification
        uses: matter-labs/zksync-ci-common/.github/actions/slack-notify-release@aba-webhook-trigger
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          context: 'TEST: webhook check'
